"""
This file is generated by genconfig v0.2.1

This file uses:
    - PyYAML from https://pypi.org/project/PyYAML/
    - marshmallow from https://marshmallow.readthedocs.io/en/stable/
"""
import os
import yaml
import warnings
from dataclasses import field, dataclass
from marshmallow import fields, Schema, post_load
__all__ = ['config']


def _environ(key, cast):
    return lambda : cast(os.environ[key])


@dataclass
class _ConfigModel:
    int_field: int = field(default_factory=_environ('INT_FIELD', int))
    str_field: str = field(default_factory=_environ('STR_FIELD', str))


class _ConfigSchema(Schema):
    int_field = fields.Int()
    str_field = fields.Str()

    @post_load
    def make_dataclass(self, data, many, **__ignored):
        if many:
            return [_ConfigModel(**item) for item in data]
        else:
            return _ConfigModel(**data)


__config_fn = os.path.join(os.path.dirname(__file__), 'config_sipmple.yml')
if os.path.isfile(__config_fn):
    with open(__config_fn) as f:
        config = _ConfigSchema().load(yaml.load(f, Loader=yaml.Loader))
else:
    warnings.warn('{} was not found!'.format(__config_fn), RuntimeWarning)
    config = _ConfigSchema().load({})
if __name__ == '__main__':
    print(config)
